# Importing

In [79]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\updes\\anaconda3\\Lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


# creating a tensor with constant

## Creating a Scaler tensor

In [80]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [81]:
scaler.ndim

0

## Creating a vector tensor

In [82]:
vactor = tf.constant([45,25,34])
vactor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([45, 25, 34])>

In [83]:
vactor.ndim

1

## Creating a matrix tensor 

In [84]:
matrix = tf.constant([[12,3],[14,65]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  3],
       [14, 65]])>

In [85]:
matrix.ndim

2

# Creating a tensor with variable

In [86]:
changeable_tensor = tf.Variable([12,54,9,2])
unchangeable_tensor = tf.constant([12,54,9,2])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([12, 54,  9,  2])>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([12, 54,  9,  2])>)

## change a veriable in changeable_tensor veriable

In [87]:
print(f"before  {changeable_tensor}")
print(f"after- {changeable_tensor[0].assign(7)}")

before  <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([12, 54,  9,  2])>
after- <tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 7, 54,  9,  2])>


## change a veriable in unchangeable_tensor veriable

In [88]:
print(f"before  {unchangeable_tensor}")
print(f"after- {unchangeable_tensor[0].assign(7)}")

before  [12 54  9  2]


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# creating a random tensor

In [89]:
random_1 = tf.random.Generator.from_seed(42) #seed is used for reproducibility
random_1 = random_1.normal(shape=(2,3)) #normal is for generating numbers of a normal disturabtion
random_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [90]:
tf.random.set_seed(3)
f=tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.13366318, 0.5678531 , 0.4963317 , 0.01686525, 0.50454175,
       0.74873126, 0.13033688, 0.33561492, 0.6519277 , 0.4761485 ,
       0.10387266, 0.9109869 , 0.6864439 , 0.5539956 , 0.20753646,
       0.19556391, 0.12885666, 0.28114808, 0.16677248, 0.35751677,
       0.15708935, 0.61180794, 0.01381111, 0.36667538, 0.7777628 ,
       0.22013807, 0.94583595, 0.9809965 , 0.70055914, 0.59534967,
       0.09030735, 0.7696253 , 0.8360609 , 0.6200143 , 0.00813675,
       0.9744582 , 0.92357314, 0.52688074, 0.3954196 , 0.72540176,
       0.20234585, 0.50628567, 0.11063731, 0.10722339, 0.20271766,
       0.4071225 , 0.43778348, 0.16643357, 0.6824596 , 0.54546094],
      dtype=float32)>

# Shuffle a tensor

In [91]:
not_shuffled_tensor = tf.random.Generator.from_seed(2).normal(shape=(2,3))
print(not_shuffled_tensor.ndim)
not_shuffled_tensor

2


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.1012345 , -0.2744976 ,  1.4204658 ],
       [ 1.2609464 , -0.43640924, -1.9633987 ]], dtype=float32)>

In [92]:
tf.random.shuffle(not_shuffled_tensor)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.2609464 , -0.43640924, -1.9633987 ],
       [-0.1012345 , -0.2744976 ,  1.4204658 ]], dtype=float32)>

# creating tensor with numpy

## create a tensor of all ones

In [93]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

# creating a tensor of all zeros

In [94]:
tf.zeros(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## creating tensors of identity metrixes

In [95]:
tf.eye(10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

## Creating numpy array as tensor

In [96]:
import numpy as np
numpy_array= np.arange(1,25,dtype=np.int32)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [97]:
numpy_as_tensor=tf.constant(numpy_array)
numpy_as_tensor

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [98]:
numpy_as_tensor2=tf.constant(numpy_array,shape=(2,3,4))
numpy_as_tensor2

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

# Getting information from tensors

* shape
* size
* rank
* axis or dimension

In [99]:
# create a rank 4 tensor
rank_4_tensor = tf.zeros([2,3,5,6])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 5, 6), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0.

## AXIS

In [100]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 5, 6), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]], dtype=float32)>

# Shape

In [101]:
rank_4_tensor.shape

TensorShape([2, 3, 5, 6])

# Rank

In [102]:
rank_4_tensor.ndim

4

# Size

In [103]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=180>

# expanding tensors

In [104]:
tensor2=tf.random.Generator.from_seed(42).normal(shape=(3,3))
tensor2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>

In [105]:
tf.expand_dims(tensor2,axis=-1)

<tf.Tensor: shape=(3, 3, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702],
        [ 0.07595026]],

       [[-1.2573844 ],
        [-0.23193763],
        [-1.8107855 ]],

       [[ 0.09988727],
        [-0.50998646],
        [-0.7535805 ]]], dtype=float32)>

# operators of tensorflow
(+, -, *, /)

In [106]:
tensor3=tf.Variable(np.random.randint(1,100,size=(2,3)))
tensor3

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[53, 43, 76],
       [41, 36, 33]])>

In [107]:
tensor3*10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[530, 430, 760],
       [410, 360, 330]])>

In [108]:
tf.multiply(tensor3,10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[530, 430, 760],
       [410, 360, 330]])>

In [109]:
matrix_a = tf.constant([[1, 2], [3, 4],[9,10]])
matrix_b = tf.constant([[5, 6], [7, 8],[9,10]])
# Multiplies matrix and Transposes it
tf.matmul(matrix_a,tf.transpose(matrix_b))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 17,  23,  29],
       [ 39,  53,  67],
       [105, 143, 181]])>

# Changing datatype in tensorflow

In [110]:
# change from float32 to float16 
c=tf.constant([7.0,10])
c.dtype

tf.float32

In [111]:
b=tf.cast(c,dtype=tf.float16) #reduced precision
b.dtype

tf.float16

# Aggregation in tensors

## Get The Minimum

In [112]:
tensor_aggregation=tf.Variable(np.random.randint(1,100,size=(2,50)))
tensor_aggregation

<tf.Variable 'Variable:0' shape=(2, 50) dtype=int32, numpy=
array([[14, 26, 44, 81, 79,  9, 58, 24, 25,  9, 72, 55, 41, 73,  8, 38,
        65, 73, 12, 83, 36,  8, 51, 16, 17, 78, 27, 92,  7, 53, 86,  9,
        58, 29, 97, 77, 69, 75, 69, 17, 28, 63, 82, 58, 45,  2, 55, 61,
        68, 20],
       [34, 94, 90, 55, 29, 37, 75,  5, 27, 45, 72, 27, 19, 81, 42, 52,
        19, 54, 40, 58, 65, 66, 23, 38, 95, 14, 53, 94, 83, 42, 80,  7,
        76, 35, 89, 33, 81, 19, 95, 84, 45, 13,  7, 51, 76, 95, 17, 23,
        91, 64]])>

In [113]:
tf.reduce_min(tensor_aggregation)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Get The Maximum

In [114]:
tf.reduce_max(tensor_aggregation)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

## Get The Mean

In [115]:
tf.reduce_mean(tensor_aggregation)

<tf.Tensor: shape=(), dtype=int32, numpy=49>

## Get The sum

In [116]:
tf.reduce_sum(tensor_aggregation)

<tf.Tensor: shape=(), dtype=int32, numpy=4951>

## Get The absolute

In [117]:
d=tf.constant([-7,-10,2])
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ -7, -10,   2])>

In [118]:
tf.abs(d)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 10,  2])>

## Get The Variance

In [119]:
tf.math.reduce_variance(tf.cast(tensor_aggregation,dtype=tf.float32),axis=0)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([1.00000e+02, 1.15600e+03, 5.29000e+02, 1.69000e+02, 6.25000e+02,
       1.96000e+02, 7.22500e+01, 9.02500e+01, 1.00000e+00, 3.24000e+02,
       0.00000e+00, 1.96000e+02, 1.21000e+02, 1.60000e+01, 2.89000e+02,
       4.90000e+01, 5.29000e+02, 9.02500e+01, 1.96000e+02, 1.56250e+02,
       2.10250e+02, 8.41000e+02, 1.96000e+02, 1.21000e+02, 1.52100e+03,
       1.02400e+03, 1.69000e+02, 1.00000e+00, 1.44400e+03, 3.02500e+01,
       9.00000e+00, 1.00000e+00, 8.10000e+01, 9.00000e+00, 1.60000e+01,
       4.84000e+02, 3.60000e+01, 7.84000e+02, 1.69000e+02, 1.12225e+03,
       7.22500e+01, 6.25000e+02, 1.40625e+03, 1.22500e+01, 2.40250e+02,
       2.16225e+03, 3.61000e+02, 3.61000e+02, 1.32250e+02, 4.84000e+02],
      dtype=float32)>

## Get the SD

In [120]:
sd = tf.math.reduce_std(tf.cast(tensor_aggregation,dtype=tf.float32),axis=0)
sd

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([10. , 34. , 23. , 13. , 25. , 14. ,  8.5,  9.5,  1. , 18. ,  0. ,
       14. , 11. ,  4. , 17. ,  7. , 23. ,  9.5, 14. , 12.5, 14.5, 29. ,
       14. , 11. , 39. , 32. , 13. ,  1. , 38. ,  5.5,  3. ,  1. ,  9. ,
        3. ,  4. , 22. ,  6. , 28. , 13. , 33.5,  8.5, 25. , 37.5,  3.5,
       15.5, 46.5, 19. , 19. , 11.5, 22. ], dtype=float32)>

# find the posation of the max and min

In [121]:
sd[tf.argmax(sd)]

<tf.Tensor: shape=(), dtype=float32, numpy=46.5>

In [122]:
sd[tf.argmin(sd)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

## squeeze the dim of tensor

In [123]:
g=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.3532257 , 0.78826356, 0.00478339, 0.05605543, 0.4563142 ,
           0.45365882, 0.05809855, 0.91033745, 0.529439  , 0.9014213 ,
           0.1678977 , 0.76625216, 0.71933055, 0.73373806, 0.80966103,
           0.48611605, 0.5024513 , 0.61660206, 0.6842716 , 0.4888047 ,
           0.38183975, 0.6499039 , 0.6901411 , 0.45677352, 0.13887179,
           0.83528817, 0.59171   , 0.44016612, 0.55080235, 0.269938  ,
           0.41178274, 0.06189823, 0.57662535, 0.78262675, 0.6395564 ,
           0.02375031, 0.6288619 , 0.9487469 , 0.11811757, 0.95076084,
           0.6718377 , 0.08483505, 0.961607  , 0.19454622, 0.40590465,
           0.30409443, 0.62665665, 0.21923673, 0.19704616, 0.10154283]]]]],
      dtype=float32)>

In [124]:
g_squeezed=tf.squeeze(g)
g_squeezed #remove all the dim with no value

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.3532257 , 0.78826356, 0.00478339, 0.05605543, 0.4563142 ,
       0.45365882, 0.05809855, 0.91033745, 0.529439  , 0.9014213 ,
       0.1678977 , 0.76625216, 0.71933055, 0.73373806, 0.80966103,
       0.48611605, 0.5024513 , 0.61660206, 0.6842716 , 0.4888047 ,
       0.38183975, 0.6499039 , 0.6901411 , 0.45677352, 0.13887179,
       0.83528817, 0.59171   , 0.44016612, 0.55080235, 0.269938  ,
       0.41178274, 0.06189823, 0.57662535, 0.78262675, 0.6395564 ,
       0.02375031, 0.6288619 , 0.9487469 , 0.11811757, 0.95076084,
       0.6718377 , 0.08483505, 0.961607  , 0.19454622, 0.40590465,
       0.30409443, 0.62665665, 0.21923673, 0.19704616, 0.10154283],
      dtype=float32)>

## OnehotEncode the tensors

In [125]:
some_list=[0,1,2,3]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [126]:
tf.one_hot(some_list, depth=4, on_value=225,off_value=-1)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[225,  -1,  -1,  -1],
       [ -1, 225,  -1,  -1],
       [ -1,  -1, 225,  -1],
       [ -1,  -1,  -1, 225]])>

# Some More functions

In [127]:
# creating a tensor
A = tf.range(1,10)
A

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [128]:
# find the square
tf.square(A)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [129]:
# find the square_root
tf.sqrt(tf.cast(A,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [130]:
# find the log
tf.math.log(tf.cast(A,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

**Note: (** converting numpy into tensor will cause it type to change from **int32 to int64 )**

# Using / Checking the GPUs

In [132]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [133]:
!nvidia-smi

Sat Nov  8 19:04:03 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 572.83                 Driver Version: 572.83         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8              5W /   50W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
!